/**
 * Branding & store configuration — edit this file to rebrand.
 */

export const store = {
  storeName: "France Mobilier",
  storeTagline:
    "Des meubles sélectionnés pour gagner en confort, en espace et en simplicité au quotidien.",
  tagline: "Des meubles sélectionnés pour gagner en confort, en espace et en simplicité au quotidien.",
  domain: "https://francemobilier.com",
  supportEmail: "contact@francemobilier.com",
  /** Horaires affichés publiquement (bandeau, contact). */
  supportHoursShort: "lun–ven 10h–22h",
  supportHours: "Du lundi au vendredi, de 10h à 22h",
  country: "FR",
  currency: "EUR",
  locale: "fr-FR",
  logoPath: "/logo-france-mobilier.png",
  /** Raison sociale affichée : DPSP. */
  companyName: "DPSP",
  companyLegalForm: "Entrepreneur individuel",
  companyTradeName: "DPSP",
  /** Rue non diffusible INSEE (statut P) — ville confirmée : Lyon 4e. */
  companyAddress: "",
  companyCity: "Lyon",
  companyPostalCode: "69004",
  companyCountry: "France",
  companySiren: "882 131 071",
  companySiret: "882 131 071 00038",
  companyRegistration: "SIREN 882 131 071 — SIRET 882 131 071 00038",
  companyNaf: "47.91B — Vente à distance sur catalogue spécialisé",
  vatNumber: "",
  phone: "",
  returnAddress: "",
  socials: {
    instagram: "",
    facebook: "",
    pinterest: "",
  },
} as const;

export const navigation = [
  { href: "/nouveautes", label: "Nouveautés" },
  { href: "/collections/salon", label: "Salon" },
  { href: "/collections/chambre", label: "Chambre" },
  { href: "/collections/entree-rangement", label: "Entrée & rangement" },
  { href: "/collections/bureau", label: "Bureau" },
  { href: "/collections/petits-espaces", label: "Petits espaces" },
] as const;

export const secondaryNavigation = [
  { href: "/collections/meubles", label: "Tous les meubles" },
  { href: "/guides", label: "Conseils" },
  { href: "/collections/animaux", label: "Animaux" },
  { href: "/pro", label: "Professionnels" },
  { href: "/contact", label: "Contact" },
] as const;

export const collections = [
  {
    slug: "salon",
    name: "Salon",
    description: "Tables, meubles TV et pièces choisies pour un salon plus simple à vivre.",
    rooms: ["salon"] as const,
    image: "/lifestyle/maison.jpg",
  },
  {
    slug: "chambre",
    name: "Chambre",
    description: "Chevets, coiffeuses et petits meubles pour organiser la chambre.",
    rooms: ["chambre"] as const,
    image: "/lifestyle/marque.jpg",
  },
  {
    slug: "entree-rangement",
    name: "Entrée & rangement",
    description: "Des meubles pratiques pour organiser l’entrée et optimiser les espaces étroits.",
    rooms: ["entree"] as const,
    image: "/lifestyle/rangement.jpg",
  },
  {
    slug: "bureau",
    name: "Bureau",
    description: "Bureaux et rangements pour travailler chez soi sans encombrer la pièce.",
    rooms: ["bureau"] as const,
    image: "/lifestyle/bureau.jpg",
  },
  {
    slug: "petits-espaces",
    name: "Petits espaces",
    description: "Des meubles sélectionnés pour gagner en confort sans perdre de place.",
    smallSpace: true,
    image: "/lifestyle/petits-espaces.jpg",
  },
  {
    slug: "meubles",
    name: "Tous les meubles",
    description: "La sélection France Mobilier, sans les accessoires.",
    rooms: ["salon", "chambre", "entree", "bureau"] as const,
    secondary: true,
  },
  {
    slug: "tables-basses",
    name: "Tables basses",
    description: "Des tables basses compactes, choisies pour les salons où chaque centimètre compte.",
    productTypes: ["table-basse"] as const,
    secondary: true,
  },
  {
    slug: "meubles-tv",
    name: "Meubles TV",
    description: "Des meubles TV peu profonds pour rester le long du mur.",
    productTypes: ["meuble-tv"] as const,
    secondary: true,
  },
  {
    slug: "tables-a-manger",
    name: "Tables à manger",
    description: "Des tables à manger extensibles pour les pièces qui doivent rester souples.",
    productTypes: ["table-a-manger"] as const,
    secondary: true,
  },
  {
    slug: "tables-de-chevet",
    name: "Tables de chevet",
    description: "Des tables de chevet aux dimensions lisibles, pour les chambres compactes.",
    productTypes: ["table-de-chevet"] as const,
    secondary: true,
  },
  {
    slug: "coiffeuses",
    name: "Coiffeuses",
    description: "Des coiffeuses choisies pour leur format et leur usage quotidien.",
    productTypes: ["coiffeuse"] as const,
    secondary: true,
  },
  {
    slug: "meubles-chaussures",
    name: "Meubles à chaussures",
    description: "Des meubles à chaussures sélectionnés pour optimiser l’entrée, y compris les espaces étroits.",
    productTypes: ["meuble-chaussures"] as const,
    secondary: true,
  },
  {
    slug: "casiers",
    name: "Meubles à casiers",
    description: "Des casiers peu profonds pour ranger le long d’un mur.",
    productTypes: ["casiers"] as const,
    secondary: true,
  },
  {
    slug: "buffets",
    name: "Buffets",
    description: "Des buffets bas pour le salon, sans occuper tout le mur.",
    productTypes: ["buffet"] as const,
    secondary: true,
  },
  {
    slug: "consoles",
    name: "Consoles",
    description: "Des consoles peu profondes pour le salon ou l’entrée.",
    productTypes: ["console"] as const,
    secondary: true,
  },
  {
    slug: "commodes",
    name: "Commodes",
    description: "Des commodes pour ranger la chambre sans l’encombrer.",
    productTypes: ["commode"] as const,
    secondary: true,
  },
  {
    slug: "armoires",
    name: "Armoires",
    description: "Des armoires étroites pour les chambres d’appartement.",
    productTypes: ["armoire"] as const,
    secondary: true,
  },
  {
    slug: "accessoires",
    name: "Accessoires",
    description: "Des accessoires pour compléter un meuble, pas pour définir le catalogue.",
    rooms: ["accessoires"] as const,
    secondary: true,
  },
  {
    slug: "animaux",
    name: "Animaux",
    description: "Du pratique sans sacrifier votre intérieur.",
    categories: ["animaux"] as const,
    rooms: ["accessoires"] as const,
    secondary: true,
    image: "/lifestyle/animaux.jpg",
  },
  {
    slug: "maison",
    name: "Maison",
    description: "Salon et chambre : les meubles du quotidien.",
    rooms: ["salon", "chambre"] as const,
    secondary: true,
    image: "/lifestyle/maison.jpg",
  },
  {
    slug: "rangement",
    name: "Rangement",
    description: "Entrée et rangements pensés pour gagner de la place.",
    rooms: ["entree"] as const,
    secondary: true,
    image: "/lifestyle/rangement.jpg",
  },
] as const;
